open module com.mastfrog.jackson.mongodb {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.acteur.mongo.impl;

    // derived from com.fasterxml.jackson.core/jackson-databind-2.13.2.2 in com/fasterxml/jackson/core/jackson-databind/2.13.2.2/jackson-databind-2.13.2.2.pom
    requires transitive com.fasterxml.jackson.databind;
    requires transitive com.mastfrog.annotation.processors;
    requires transitive com.mastfrog.jackson;

    // derived from org.mongodb/mongo-java-driver-3.12.11 in org/mongodb/mongo-java-driver/3.12.11/mongo-java-driver-3.12.11.pom
    requires transitive org.mongodb.mongo.java.driver;

}
