// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.jackson.mongodb {
    exports com.mastfrog.acteur.mongo.impl;

    // Sibling com.mastfrog/annotation-processors-3.0.0-dev:compile
    requires com.mastfrog.annotation.processors;

    // Sibling com.mastfrog/jackson-3.0.0-dev
    requires com.mastfrog.jackson;

    // derived from com.fasterxml.jackson.core/jackson-databind-0.0.0-? in com/fasterxml/jackson/core/jackson-databind/2.9.9.3/jackson-databind-2.9.9.3.pom
    requires transitive com.fasterxml.jackson.databind;

    // derived from org.mongodb/mongo-java-driver-0.0.0-? in org/mongodb/mongo-java-driver/3.12.11/mongo-java-driver-3.12.11.pom
    requires mongo.java.driver;
    provides com.mastfrog.jackson.JacksonConfigurer with
       com.mastfrog.acteur.mongo.impl.JacksonMongoDB;

}
