open module com.mastfrog.jackson.jodatime {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.jackson.jodatime;

    // derived from com.fasterxml.jackson.core/jackson-databind-2.13.2.2 in com/fasterxml/jackson/core/jackson-databind/2.13.2.2/jackson-databind-2.13.2.2.pom
    requires transitive com.fasterxml.jackson.databind;

    // derived from com.fasterxml.jackson.datatype/jackson-datatype-joda-2.13.2 in com/fasterxml/jackson/datatype/jackson-datatype-joda/2.13.2/jackson-datatype-joda-2.13.2.pom
    requires transitive com.fasterxml.jackson.datatype.joda;
    requires transitive com.mastfrog.annotation.processors;
    requires transitive com.mastfrog.jackson;

}
