// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.jackson.jodatime {
    exports com.mastfrog.jackson.jodatime;

    // derived from com.fasterxml.jackson.datatype/jackson-datatype-joda-0.0.0-? in com/fasterxml/jackson/datatype/jackson-datatype-joda/2.13.2/jackson-datatype-joda-2.13.2.pom
    requires transitive com.fasterxml.jackson.datatype.joda;

    // Sibling com.mastfrog/annotation-processors-3.0.0-dev:compile
    requires com.mastfrog.annotation.processors;

    // Sibling com.mastfrog/jackson-3.0.0-dev

    // Transitive detected by source scan
    requires com.mastfrog.jackson;

    // derived from com.fasterxml.jackson.core/jackson-databind-0.0.0-? in com/fasterxml/jackson/core/jackson-databind/2.9.9.3/jackson-databind-2.9.9.3.pom
    requires com.fasterxml.jackson.databind;
    provides com.mastfrog.jackson.JacksonConfigurer with
       com.mastfrog.jackson.jodatime.JodeTimeJacksonConfigurer;

}
