open module com.mastfrog.email.base {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.email.server;
    requires transitive com.mastfrog.url;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
