// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.email.server {
    exports com.mastfrog.email.server;

    // derived from javax.activation/activation-1.1.1 in javax/activation/activation/1.1.1/activation-1.1.1.pom
    requires activation;
    requires javax.mail;

    // derived from com.google.inject.extensions/guice-multibindings-0.0.0-? in com/google/inject/extensions/guice-multibindings/4.2.3/guice-multibindings-4.2.3.pom
    requires com.google.guice.extensions.multibindings;

    // Inferred from source scan
    requires com.mastfrog.collections;

    // Sibling com.mastfrog/email-base-3.0.0-dev
    requires com.mastfrog.email.base;

    // Sibling com.mastfrog/giulius-3.0.0-dev
    requires com.mastfrog.giulius;

    // Sibling com.mastfrog/giulius-settings-3.0.0-dev

    // Transitive detected by source scan
    requires com.mastfrog.giulius.settings;
    requires com.mastfrog.giulius.tests;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan
    requires com.mastfrog.streams;

    // Sibling com.mastfrog/url-3.0.0-dev
    requires com.mastfrog.url;

    // derived from org.apache.commons/commons-email-1.5 in org/apache/commons/commons-email/1.5/commons-email-1.5.pom
    requires commons.email;

    // derived from org.freemarker/freemarker-2.3.31 in org/freemarker/freemarker/2.3.31/freemarker-2.3.31.pom
    requires freemarker;
    requires java.logging;

    // derived from junit/junit-4.13.2:compile in junit/junit/4.13.2/junit-4.13.2.pom
    requires junit;
}
