open module com.mastfrog.email.server {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.email.server;

    // derived from com.google.inject.extensions/guice-multibindings-4.2.3 in com/google/inject/extensions/guice-multibindings/4.2.3/guice-multibindings-4.2.3.pom
    requires transitive com.google.inject.extensions.guice.multibindings;
    requires transitive com.mastfrog.email.base;
    requires transitive com.mastfrog.giulius;
    requires transitive com.mastfrog.giulius.settings;
    requires transitive com.mastfrog.giulius.tests;
    requires transitive com.mastfrog.url;
    requires java.logging;

    // derived from javax.activation/activation-1.1.1 in javax/activation/activation/1.1.1/activation-1.1.1.pom
    requires transitive javax.activation.activation;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

    // derived from org.apache.commons/commons-email-1.5 in org/apache/commons/commons-email/1.5/commons-email-1.5.pom
    requires transitive org.apache.commons.commons.email;

    // derived from org.freemarker/freemarker-2.3.31 in org/freemarker/freemarker/2.3.31/freemarker-2.3.31.pom
    requires transitive org.freemarker.freemarker;

}
