open module com.mastfrog.embedded.jetty {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.grizzly;

    // derived from com.google.inject.extensions/guice-servlet-5.1.0 in com/google/inject/extensions/guice-servlet/5.1.0/guice-servlet-5.1.0.pom
    requires transitive com.google.inject.extensions.guice.servlet;
    requires transitive com.mastfrog.giulius;
    requires transitive com.mastfrog.giulius.servlet;
    requires java.logging;

    // derived from javax.servlet/javax.servlet-api-4.0.1 in javax/servlet/javax.servlet-api/4.0.1/javax.servlet-api-4.0.1.pom
    requires transitive javax.servlet.javax.servlet.api;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

    // derived from org.apache.httpcomponents/httpasyncclient-4.1.5 in org/apache/httpcomponents/httpasyncclient/4.1.5/httpasyncclient-4.1.5.pom
    requires transitive org.apache.httpcomponents.httpasyncclient;

    // derived from org.apache.httpcomponents/httpcore-4.4.15 in org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.pom
    requires transitive org.apache.httpcomponents.httpcore;

    // derived from org.eclipse.jetty/jetty-http-9.4.44.v20210927 in org/eclipse/jetty/jetty-http/9.4.44.v20210927/jetty-http-9.4.44.v20210927.pom
    requires transitive org.eclipse.jetty.jetty.http;

    // derived from org.eclipse.jetty/jetty-io-9.4.44.v20210927 in org/eclipse/jetty/jetty-io/9.4.44.v20210927/jetty-io-9.4.44.v20210927.pom
    requires transitive org.eclipse.jetty.jetty.io;

    // derived from org.eclipse.jetty/jetty-server-9.4.44.v20210927 in org/eclipse/jetty/jetty-server/9.4.44.v20210927/jetty-server-9.4.44.v20210927.pom
    requires transitive org.eclipse.jetty.jetty.server;

    // derived from org.eclipse.jetty/jetty-webapp-9.4.44.v20210927 in org/eclipse/jetty/jetty-webapp/9.4.44.v20210927/jetty-webapp-9.4.44.v20210927.pom
    requires transitive org.eclipse.jetty.jetty.webapp;

}
