// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.jackson {
    exports com.mastfrog.jackson;

    requires com.google.common;
    // derived from com.google.inject/guice-0.0.0-? in com/google/inject/guice/5.1.0/guice-5.1.0.pom
    requires com.google.guice;

    // Sibling com.mastfrog/annotation-processors-3.0.0-dev:compile
    requires com.mastfrog.annotation.processors;
    requires com.mastfrog.giulius.tests;

    // Inferred from source scan

    // Sibling com.mastfrog/util-time-3.0.0-dev
    requires com.mastfrog.time;

    // Sibling com.mastfrog/util-function-3.0.0-dev
    requires com.mastfrog.util.function;

    // derived from com.fasterxml.jackson.core/jackson-databind-0.0.0-? in com/fasterxml/jackson/core/jackson-databind/2.9.9.3/jackson-databind-2.9.9.3.pom
    requires transitive com.fasterxml.jackson.databind;

    // Inferred from test-source-scan
    requires junit;
    provides com.mastfrog.jackson.JacksonConfigurer with
       com.mastfrog.jackson.JavaTimeConfigurer,
       com.mastfrog.jackson.LocaleJacksonConfigurer,
       com.mastfrog.jackson.OptionalJavaUtilSerializer,
       com.mastfrog.jackson.OptionalSerializer;

}
