open module com.mastfrog.jackson {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.jackson;

    // derived from com.fasterxml.jackson.core/jackson-databind-2.13.2.2 in com/fasterxml/jackson/core/jackson-databind/2.13.2.2/jackson-databind-2.13.2.2.pom
    requires transitive com.fasterxml.jackson.databind;

    // derived from com.google.inject/guice-5.1.0 in com/google/inject/guice/5.1.0/guice-5.1.0.pom
    requires transitive com.google.inject.guice;
    requires transitive com.mastfrog.annotation.processors;
    requires transitive com.mastfrog.giulius.tests;
    requires transitive com.mastfrog.util.function;
    requires transitive com.mastfrog.util.time;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
