// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.email.base {
    exports com.mastfrog.email;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Sibling com.mastfrog/url-3.0.0-dev
    requires com.mastfrog.url;

    // Inferred from test-source-scan
    requires transitive junit;

}
