// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.embedded.jetty {
    exports com.mastfrog.grizzly;

    // derived from com.google.inject.extensions/guice-servlet-0.0.0-? in com/google/inject/extensions/guice-servlet/5.1.0/guice-servlet-5.1.0.pom
    requires com.google.guice.extensions.servlet;

    // Sibling com.mastfrog/giulius-3.0.0-dev
    requires com.mastfrog.giulius;

    // Sibling com.mastfrog/giulius-servlet-3.0.0-dev
    requires com.mastfrog.giulius.servlet;

    // Transitive detected by source scan
    requires com.mastfrog.giulius.settings;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan
    requires com.mastfrog.streams;
    requires java.logging;

    // derived from javax.servlet/javax.servlet-api-4.0.1 in javax/servlet/javax.servlet-api/4.0.1/javax.servlet-api-4.0.1.pom
    requires javax.servlet.api;

    // Inferred from test-source-scan
    requires junit;

    // derived from org.eclipse.jetty/jetty-http-0.0.0-? in org/eclipse/jetty/jetty-http/9.4.44.v20210927/jetty-http-9.4.44.v20210927.pom
    requires org.eclipse.jetty.http;

    // derived from org.eclipse.jetty/jetty-io-0.0.0-? in org/eclipse/jetty/jetty-io/9.4.44.v20210927/jetty-io-9.4.44.v20210927.pom
    requires org.eclipse.jetty.io;

    // derived from org.eclipse.jetty/jetty-server-0.0.0-? in org/eclipse/jetty/jetty-server/9.4.44.v20210927/jetty-server-9.4.44.v20210927.pom
    requires org.eclipse.jetty.server;
    requires org.eclipse.jetty.servlet;
    requires org.eclipse.jetty.security;
    requires org.eclipse.jetty.util;

    // derived from org.eclipse.jetty/jetty-webapp-0.0.0-? in org/eclipse/jetty/jetty-webapp/9.4.44.v20210927/jetty-webapp-9.4.44.v20210927.pom
    requires org.eclipse.jetty.webapp;

}
