// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.giulius.servlet {
    exports com.mastfrog.giulius.http;

    // derived from com.google.inject.extensions/guice-servlet-0.0.0-? in com/google/inject/extensions/guice-servlet/5.1.0/guice-servlet-5.1.0.pom
    requires com.google.guice.extensions.servlet;

    // Inferred from source scan
    requires com.mastfrog.function;

    // Sibling com.mastfrog/giulius-3.0.0-dev
    requires com.mastfrog.giulius;

    // Sibling com.mastfrog/giulius-annotation-processors-3.0.0-dev:compile
    requires static com.mastfrog.giulius.annotation.processors;

    // Sibling com.mastfrog/giulius-annotations-3.0.0-dev
    requires com.mastfrog.giulius.annotations;

    // Transitive detected by source scan
    requires com.mastfrog.giulius.settings;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Sibling com.mastfrog/scopes-3.0.0-dev
    requires com.mastfrog.scopes;

    // Inferred from source scan
    requires com.mastfrog.streams;

    // derived from javax.servlet/servlet-api-2.5:provided in javax/servlet/servlet-api/2.5/servlet-api-2.5.pom
    requires servlet.api;

}
