open module com.mastfrog.giulius.servlet {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.giulius.http;

    // derived from com.google.inject.extensions/guice-servlet-5.1.0 in com/google/inject/extensions/guice-servlet/5.1.0/guice-servlet-5.1.0.pom
    requires transitive com.google.inject.extensions.guice.servlet;
    requires transitive com.mastfrog.giulius;
    requires transitive com.mastfrog.giulius.annotation.processors;
    requires transitive com.mastfrog.giulius.annotations;
    requires transitive com.mastfrog.scopes;

    // derived from javax.servlet/servlet-api-2.5 in javax/servlet/servlet-api/2.5/servlet-api-2.5.pom
    requires transitive javax.servlet.servlet.api;

}
