open module com.mastfrog.statistics {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.statistics;
    requires transitive com.mastfrog.giulius;
    requires transitive com.mastfrog.giulius.annotation.processors;
    requires transitive com.mastfrog.giulius.annotations;
    requires transitive com.mastfrog.util.misc;
    requires transitive com.mastfrog.util.net;
    requires java.logging;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
