// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.statistics {
    exports com.mastfrog.statistics;

    requires java.management;

    // Sibling com.mastfrog/giulius-3.0.0-dev
    // Transitive detected by source scan
    requires com.mastfrog.giulius;

    // Sibling com.mastfrog/giulius-annotation-processors-3.0.0-dev:compile
    requires com.mastfrog.giulius.annotation.processors;

    // Sibling com.mastfrog/giulius-annotations-3.0.0-dev
    requires com.mastfrog.giulius.annotations;
    requires com.mastfrog.giulius.settings;

    // Inferred from source scan
    // Sibling com.mastfrog/util-misc-3.0.0-dev
    requires com.mastfrog.misc;

    // Sibling com.mastfrog/util-net-3.0.0-dev
    requires com.mastfrog.net;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan
    requires com.mastfrog.util.function;
    requires java.logging;

    // Inferred from test-source-scan
    requires junit;
}
